### ISSUE TITLE
Merge two videos, the merged video will be stuck in the last few seconds

### ISSUE THREAD

**Issue by jamesh23** [transitive-bullshit/ffmpeg-concat#99]
the second video last few seconds image frame will lost, does anyone know why ?

**Comment by zdying** [comment]
I have the same issue. anyone can tell why?

**Comment by jamesh23** [comment]
@transitive-bullshit Please help, thank you

**Comment by morohit** [comment]
Same to me. Runing on debian 10

**Comment by morohit** [comment]
This temporary solution works for me:
In `lib/transcode-video.js`, deactivate the audio option `-shortest` (just comment out the line).

**Comment by jamesh23** [comment]
> This temporary solution works for me:
> In `lib/transcode-video.js`, deactivate the audio option `-shortest` (just comment out the line).

it works for me too

**Comment by transitive-bullshit** [comment]
@jamesh23 @morohit are you using audio? That option should only be included if audio is accompanying the videos.

It's been awhile since I've tested this, but I'm pretty sure that's in there so that longer audio tracks don't result in output videos where the video stream ends early and the audio stream keeps going.

**Comment by transitive-bullshit** [comment]
I just published a version `1.3.3` which should resolve this issue.

**Comment by jamesh23** [comment]
> I just published a version `1.3.3` which should resolve this issue.

thank you ~
